### PR TITLE
add test cases

### PR DESCRIPTION
**Pull request by BharathMonash**
Adding few test cases. Have a few more complex tests which I will update soon.

### CODE REVIEW

**Comment by mboehme** [comment]
What's the difference to PR #12?

**Comment by BharathMonash** [comment]
> What's the difference to PR #12?

PR #12 tests for the same thing but in a more comprehensive way with multiple fuzzers, benchmark and trials.

**Comment by mboehme** [comment]
So, we can close this one?

**Comment by BharathMonash** [comment]
> So, we can close this one?

Yes Marcel, even I prefer testing it the other way (#12). I think we can close this one.

**Pull request closed without merging**
